const keys = {
  Backquote: ['`', 'ё', '~', 'Ё'],
  Digit1: ['1', '1', '!', '!'],
  Digit2: ['2', '2', '@', '"'],
  Digit3: ['3', '3', '#', '№'],
  Digit4: ['4', '4', '$', ';'],
  Digit5: ['5', '5', '%', '%'],
  Digit6: ['6', '6', '^', ':'],
  Digit7: ['7', '7', '&', '?'],
  Digit8: ['8', '8', '*', '*'],
  Digit9: ['9', '9', '(', '('],
  Digit0: ['0', '0', ')', ')'],
  Minus: ['-', '-', '_', '_'],
  Equal: ['=', '=', '+', '+'],
  Backspace: ['Backspace', 'Backspace', 'Backspace', 'Backspace'],

  Tab: ['Tab', 'Tab', 'Tab', 'Tab'],
  KeyQ: ['q', 'й', 'Q', 'Й'],
  KeyW: ['w', 'ц', 'W', 'Ц'],
  KeyE: ['e', 'у', 'E', 'У'],
  KeyR: ['r', 'к', 'R', 'К'],
  KeyT: ['t', 'е', 'T', 'Е'],
  KeyY: ['y', 'н', 'Y', 'Н'],
  KeyU: ['u', 'г', 'U', 'Г'],
  KeyI: ['i', 'ш', 'I', 'Ш'],
  KeyO: ['o', 'щ', 'O', 'Щ'],
  KeyP: ['p', 'з', 'P', 'З'],
  BracketLeft: ['[', 'х', '{', 'Х'],
  BracketRight: [']', 'ъ', '}', 'Ъ'],
  Delete: ['Del', 'Del', 'Del', 'Del'],

  CapsLock: ['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
  KeyA: ['a', 'ф', 'A', 'Ф'],
  KeyS: ['s', 'ы', 'S', 'Ы'],
  KeyD: ['d', 'в', 'D', 'В'],
  KeyF: ['f', 'а', 'F', 'А'],
  KeyG: ['g', 'п', 'G', 'П'],
  KeyH: ['h', 'р', 'H', 'Р'],
  KeyJ: ['j', 'о', 'J', 'О'],
  KeyK: ['k', 'л', 'K', 'Л'],
  KeyL: ['l', 'д', 'L', 'Д'],
  Semicolon: [';', 'ж', ':', 'Ж'],
  Quote: ["'", 'э', '"', 'Э'],
  Enter: ['Enter', 'Enter', 'Enter', 'Enter'],

  ShiftLeft: ['Shift', 'Shift', 'Shift', 'Shift'],
  KeyZ: ['z', 'я', 'Z', 'Я'],
  KeyX: ['x', 'ч', 'X', 'Ч'],
  KeyC: ['c', 'с', 'C', 'С'],
  KeyV: ['v', 'м', 'V', 'М'],
  KeyB: ['b', 'и', 'B', 'И'],
  KeyN: ['n', 'т', 'N', 'Т'],
  KeyM: ['m', 'ь', 'M', 'Ь'],
  Comma: [',', 'б', '<', 'Б'],
  Period: ['.', 'ю', '>', 'Ю'],
  Slash: ['/', '.', '?', ','],
  ArrowUp: ['↑', '↑', '↑', '↑'],
  ShiftRight: ['Shift', 'Shift', 'Shift', 'Shift'],

  ControlLeft: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  AltLeft: ['Alt', 'Alt', 'Alt', 'Alt'],
  Space: [' ', ' ', ' ', ' '],
  AltRight: ['Alt', 'Alt', 'Alt', 'Alt'],
  ArrowLeft: ['←', '←', '←', '←'],
  ArrowDown: ['↓', '↓', '↓', '↓'],
  ArrowRight: ['→', '→', '→', '→'],
  ControlRight: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
};

export default keys;
